### PR TITLE
add github ISSUE_TEMPLATE files

### PR DESCRIPTION
**Pull request by cliffordfajardo**
## What is the change?
Add `bug_report.yml` & `config.yml` file to enable Github's form based issue template
- https://youtu.be/qQE1BUkf2-s?t=23

## Motivation
- encourage's bug reporter's to put more care into their bug report before submission
- this may help maintainer's receive more detailed & higher quality bug report's
- adds helpful tips for user's during the process of creating a bug/issue report

## Demo of Change
this PR is similar to this one I created here for another repo recently 
- https://github.com/antvis/G6/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml

### CODE REVIEW

**Comment by cliffordfajardo** [comment]
Hi @neurosnap - I just started using this library & am very new to the Remix world 💿  thank you for sharing it! 🙏  I was looking for something like NextJS middleware 🙏

**Comment by neurosnap** [comment]
Thanks for the PR!  Unfortunately, for such a small project as this, I do not think that we need a github issue template.

**Comment by cliffordfajardo** [comment]
> Thanks for the PR! Unfortunately, for such a small project as this, I do not think that we need a github issue template. - @neurosnap 

Ok - makes sense

Would you say at this time this is more of a personal repo and are you open to improvements feature suggestions (_granted through discussion first_)

I'm going to continue using this in my personal project - thanks for this middleware package 🙏

**Comment by neurosnap** [comment]
> Would you say at this time this is more of a personal repo and are you open to improvements feature suggestions (granted through discussion first)

Absolutely open to improvements and want people to use it!

**Pull request closed without merging**
